### ISSUE TITLE
Cannot make

### ISSUE THREAD

**Issue by OPStellar** [fonzcastellanos/rcoaster#1]
Instruction is missing from ReadMe.
What command should be executed following `make`?

**Comment by fonzcastellanos** [comment]
Hello! Great question given my somewhat vague documentation.

After executing `make`, a `rcoaster` executable file will be produced in `src/`.  An example execution of `rcoaster`  looks like this:

`./rcoaster track.txt textures/grass.jpg textures/sky.jpg textures/wood.jpg`

I've updated the README with more details  in e7f6258a1f5d4951086a0052ea37980fedadbb8f. Let me know if you have any more questions or comments!

**Comment by fonzcastellanos** [comment]
I almost forgot to mention: make sure to pull the latest changes.  I fixed the path to the OpenGL helper library in  609dff8f7d02c112ce8eafc43b1ed4eb20ee10c4.
